// Types for the Microplan · Validate DIP page — client-side counterpart to
// POST /dip/validator (toolbox/apps/planfeld/dip_template.py::validate_microplan).
//
// Unlike Microplan · Combine DMP Files, this backend route is a genuine
// match: it already accepts a settlements_file + team_allocation_file and
// returns exactly the review workbook this page needs (see
// mp_validator.py::validate_daily_implementation_plan — 'dip', 'ward_review',
// 'team_review' sheets). So this page calls the real endpoint
// (api/client.ts::submitValidateDip) and does NOT re-implement the
// validation algorithm client-side.
//
// What it DOES do client-side is parse the returned .xlsx (utils/xlsx can
// read an ArrayBuffer directly) and aggregate that real output into the
// numbers this page displays — sums, counts, per-LGA breakdowns. That is
// pure post-processing of the backend's own authoritative result, not a
// re-derivation of the validation logic itself.
//
// One caveat worth carrying forward from the design review: the backend
// code's sheet-naming (`title.replace('_', ' ').title()` over the keys
// 'dip' / 'ward_review' / 'team_review') produces "Dip" / "Ward Review" /
// "Team Review" — but the sample DIP_Review.xlsx reviewed during design used
// "DIP" / "Ward" / "Team" instead, suggesting that sample was generated by a
// different script version. parseValidateDipResponse (utils/
// microplanValidateParse.ts) matches sheets by keyword rather than exact
// name to tolerate either.
//
// A second, more consequential thing surfaced during implementation (not
// caught during design): dip_tools.py::get_missing_team_codes compares each
// ward's zero-padded team codes ("006") against un-padded numbers generated
// from the allocated code range ("6") — verified verbatim against the real
// function body, not a porting guess. The two representations can never be
// equal, so the "Missing Teams" column it produces is populated for every
// single ward regardless of whether that ward is correctly staffed and
// numbered — confirmed against real data: all 225 of 225 wards, including
// the ones with perfect team-code alignment. That's on top of (not the same
// bug as) the LGA-vs-state numbering-convention mismatch that separately
// explains the raw DIP sheet's 98%+ "Team Code Validation" flag rate. The
// "Non-compliant Team Codes" card (ValidateTitleCards.tsx) still sums this
// column, since it was requested by name, but its caveat box now describes
// both issues precisely instead of attributing everything to the numbering
// convention.

export interface DipReviewRow {
  lga: string
  ward: string
  settlementId: string
  settlementName: string
  teamCode: string
  dayOfActivity: string
  teamCodeValidation: string | null // null = OK; otherwise "Team Code N is invalid"
}

export interface WardReviewRow {
  lga: string
  ward: string
  settlements: number
  teamAllocation: string | null // null = ward never matched the Team Allocation file
  expectedTeams: number | null
  dipTeams: number
  teamCountValidation: string | null // "Missing N Teams" or null
  missingTeams: string | null // comma-separated allocated code numbers never seen in this ward's DIP
}

export interface TeamReviewRow {
  lga: string
  ward: string
  teamCode: string
  settlements: number
  visitDays: string
  missingDays: string | null // comma-separated subset of "1","2","3","4"
}

export interface BreakdownSlice {
  label: string
  count: number
  pct: number
}

export interface LgaShortfall {
  lga: string
  teams: number // sum of Team Count Validation's numeric shortfall for this LGA's wards
  wards: number // how many of this LGA's wards are short at least one team
}

export interface ValidateDipAnalysis {
  dipRows: DipReviewRow[]
  wardReviews: WardReviewRow[]
  teamReviews: TeamReviewRow[]

  // Ingest note — derived from comparing the raw uploaded settlements file's
  // row count against the returned Dip sheet's distinct Settlement ID count,
  // plus the Ward Review sheet's own match/no-match state. No re-parsing of
  // the raw file's columns beyond a row count.
  rawSettlementRows: number
  settlementsCarried: number // distinct Settlement ID in the Dip sheet
  settlementsDropped: number // rawSettlementRows - settlementsCarried
  settlementsSplitAcrossTeams: number // Settlement IDs appearing more than once in the Dip sheet
  wardsMatched: number // Ward Review rows with a non-null Team Allocation
  wardsUnmatched: number

  lgaCount: number
  wardCount: number // distinct LGA+Ward pairs
  wardNameOnlyCount: number // distinct Ward name alone (can undercount — names reused across LGAs)
  fieldTeamCount: number // Team Review row count

  // Headline validation findings
  unaccountedTeams: number // sum of Team Count Validation's numeric shortfall
  unaccountedTeamWards: number // wards with a non-null Team Count Validation
  unaccountedTeamLgas: number
  nonCompliantTeamCodes: number // sum of Missing Teams entry counts across all wards
  nonCompliantTeamCodeWards: number // wards with a non-null Missing Teams
  teamsMissingDays: number
  teamsMissingDaysPct: number

  missingByDay: { day: '1' | '2' | '3' | '4'; count: number }[]
  unaccountedTeamsByLga: LgaShortfall[]
}
