import { Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import type { DipGeneratorAnalysis } from '../../types/dipGenerator'

interface DipGeneratorLgaChartProps {
  analysis: DipGeneratorAnalysis
  activeLga?: string | null
  onSelect?: (lga: string) => void
}

const BAR_COLOR = '#2c5f9e'
const ROW_HEIGHT = 22

// Same horizontal-bar-per-LGA pattern as DipMergerLgaChart.tsx /
// h2h/LgaBreakdownChart.tsx. analysis.teamsByLga already comes sorted
// descending. Bars are click-to-filter — DipGeneratorPage keeps one lgaFilter
// state shared with TeamDipTable's own LGA <select>, so either can drive it.
export default function DipGeneratorLgaChart({ analysis, activeLga, onSelect }: DipGeneratorLgaChartProps) {
  const data = analysis.teamsByLga
  const chartHeight = Math.max(240, data.length * ROW_HEIGHT)

  return (
    <div
      style={{
        background: 'var(--color-surface)',
        border: '1px solid var(--color-border)',
        borderRadius: 'var(--radius-lg)',
        boxShadow: 'var(--shadow-sm)',
        padding: 16,
        marginBottom: 16,
      }}
    >
      <h2 style={{ fontSize: 13, margin: '0 0 3px' }}>Team DIPs generated by LGA</h2>
      <div style={{ fontSize: 11.5, color: 'var(--color-text-muted)', marginBottom: 12 }}>
        Count of individual team PDFs per LGA, read back from the real response filenames.
        {onSelect ? ' Click a bar to filter the table below.' : ''}
      </div>
      {data.length === 0 ? (
        <div style={{ padding: 40, textAlign: 'center', color: 'var(--color-text-muted)', fontSize: 13 }}>
          No team DIPs came back yet.
        </div>
      ) : (
        <div style={{ maxHeight: 520, overflowY: 'auto' }}>
          <ResponsiveContainer width="100%" height={chartHeight}>
            <BarChart data={data} layout="vertical" margin={{ left: 8, right: 24, top: 4, bottom: 4 }}>
              <CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="var(--color-border)" />
              <XAxis type="number" allowDecimals={false} tick={{ fontSize: 11 }} />
              <YAxis type="category" dataKey="lga" width={130} tick={{ fontSize: 11 }} interval={0} />
              <Tooltip formatter={(value: number) => [value.toLocaleString(), 'Team DIPs']} />
              <Bar
                dataKey="teams"
                barSize={12}
                radius={[0, 2, 2, 0]}
                onClick={(entry: { lga: string }) => onSelect?.(entry.lga)}
                cursor={onSelect ? 'pointer' : undefined}
              >
                {data.map((entry) => (
                  <Cell
                    key={entry.lga}
                    fill={BAR_COLOR}
                    fillOpacity={!activeLga || activeLga === entry.lga ? 1 : 0.35}
                    stroke={activeLga === entry.lga ? BAR_COLOR : undefined}
                    strokeWidth={activeLga === entry.lga ? 1.5 : 0}
                  />
                ))}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </div>
      )}
    </div>
  )
}
