import StatCard from '../common/StatCard'
import type { DipGeneratorAnalysis } from '../../types/dipGenerator'

interface DipGeneratorTitleCardsProps {
  analysis: DipGeneratorAnalysis
}

// Composition cards. There used to be a validate_dip caveat box here too,
// but it described the wrong failure mode (claimed the route silently
// ignores validate_dip and returns the same output) — see
// DipGeneratorPage.tsx's own comment for the corrected, code-traced finding
// (validate_dip=True actually crashes every batch with a KeyError) and the
// caveat card that now carries that explanation instead, next to batch
// progress rather than down here where a crashed run would never reach.
export default function DipGeneratorTitleCards({ analysis }: DipGeneratorTitleCardsProps) {
  return (
    <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', marginBottom: 16 }}>
      <StatCard
        label="Team DIP PDFs"
        value={analysis.totalTeams.toLocaleString()}
        accentColor="#2c5f9e"
        hint="one per unique LGA · Ward · Team-code group — see table below"
      />
      <StatCard label="LGAs" value={analysis.lgaCount.toLocaleString()} accentColor="#2c5f9e" hint="see teams generated by LGA below" />
      <StatCard label="Wards" value={analysis.wardCount.toLocaleString()} accentColor="#2c5f9e" hint="distinct LGA · Ward groups covered" />
    </div>
  )
}
